---
name: Build firmware
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      gputils: "http://downloads.sourceforge.net/\
        project/gputils/gputils/1.5.0/gputils-1.5.2.tar.bz2"
      gpsim: "https://downloads.sourceforge.net/\
        project/gpsim/gpsim/0.32.0/gpsim-0.32.1.tar.gz"

    steps:
      - name: Install necessary packages
        run: sudo apt install -y libpopt-dev

      - name: Install gputils
        run: |
          wget -qO- $gputils | tar xjv
          cd gputils-1.5.2
          ./configure
          make -j2
          sudo make install-exec install-data

      - name: Install gpsim
        run: |
          wget -qO- $gpsim | tar xzv
          cd gpsim-0.32.1
          ./configure --disable-gui
          make -j2
          sudo make install

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Build the firmware
        run: make gateway.hex diagnose.hex interface.hex

      - name: Build chmodule
        run: |
          cd chmodule
          ./autogen.sh
          ./configure
          make

      - name: Run test suite
        run: make test

      - name: Rename firmware to tag or commit hash
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${{ github.ref_name }} # Get the tag name
          else
            TAG=$(echo "${{ github.sha }}" | cut -c1-7) # Use the short commit hash
          fi

          mv gateway.hex gateway-${TAG}.hex
          mv gateway.cod gateway-${TAG}.cod
          mv gateway.lst gateway-${TAG}.lst
          mv gateway.map gateway-${TAG}.map
          mv diagnose.hex diagnose-${TAG}.hex
          mv diagnose.cod diagnose-${TAG}.cod
          mv diagnose.lst diagnose-${TAG}.lst
          mv diagnose.map diagnose-${TAG}.map
          mv interface.hex interface-${TAG}.hex
          mv interface.cod interface-${TAG}.cod
          mv interface.lst interface-${TAG}.lst
          mv interface.map interface-${TAG}.map

      - name: Upload gateway firmware
        uses: actions/upload-artifact@v4
        with:
          name: gateway-${TAG}
          path: |
            gateway*.hex
            gateway*.cod
            gateway*.lst
            gateway*.map

      - name: Upload diagnose firmware
        uses: actions/upload-artifact@v4
        with:
          name: diagnose-${TAG}
          path: |
            diagnose*.hex
            diagnose*.cod
            diagnose*.lst
            diagnose*.map

      - name: Upload interface firmware
        uses: actions/upload-artifact@v4
        with:
          name: interface-${TAG}
          path: |
            interface*.hex
            interface*.cod
            interface*.lst
            interface*.map

      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gateway*.hex
            diagnose*.hex
            interface*.hex
          token: ${{ secrets.GITHUB_TOKEN }}
